version: '3'

services:
  pytorch-ngc:
    container_name: inaki_pytorch
    image: nvdivia-pytorch-vitkd
    build:
        context: .
        dockerfile: Dockerfile
    ipc: host
    tty: true
    ulimits:
      memlock: -1
      stack: 67108864
    ports:
      - '8888:8888'
    volumes:
      - '.:/app'
      - '/home-net/ierregue/research/data:/data'
    command: "python train.py"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ 'gpu' ]