version: '3'

services:
  pytorch-ngc:
    container_name: inaki_pytorch
    image: nvdivia-pytorch-vitkd:v7
    user: 10028:10000
    build:
        context: .
        dockerfile: Dockerfile
    ipc: host
    tty: true
    ulimits:
      memlock: -1
      stack: 67108864
    ports:
      - '6006:6006'
      - '12355:12355'
    volumes:
      - '.:/app'
      - '/home-net/ierregue/research/data:/data'
      - '/data-slow/hupba/ierregue/research/vit_kd/saved:/saved'
    #command: bash -c "python train.py"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ 'gpu' ]